spring.application.name=backend
spring.datasource.url=jdbc:mysql://root:BBtJEMRcNfQRNcqAKJmTjXGmaNdFPTkA@junction.proxy.rlwy.net:25451/railway
spring.datasource.username=root
spring.datasource.password=BBtJEMRcNfQRNcqAKJmTjXGmaNdFPTkA

# Muestra las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configura la estrategia de generación de tablas
spring.jpa.hibernate.ddl-auto=create